[credentials]
openai_api_key = "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"
mongo_uri = "mongodb+srv://rudranshsharma:excoda@testcluster.3nzv09x.mongodb.net/?retryWrites=true&w=majority&appName=TestCluster"
gemini_api_key = "AIzaSyBU5_bFsPrFZQ2kNooaNJ_uQ68G9p7aX-o"
